my_site/blog/urls.py
from django.contrib import admin
from django.urls import path

from .views import (post_list, post_detail, email_post_share,
                    post_search
                   )
from .apps import BlogConfig
from .feeds import LatestPostsFeed


app_name = BlogConfig.name

urlpatterns = [
    path('', post_list, name=f'{post_list.__name__}'),
    # path('', PostListView.as_view(), name=f'{post_list.__name__}'),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        post_detail,
        name = f'{post_detail.__name__}'
    ),
    path(
        '<int:post_id>/share/',
        email_post_share,
        name = f'{email_post_share.__name__}'
    ),
    path(
        'tag/<slug:tag_slug>/',
        post_list,
        name = f'{post_list.__name__}_by_tag'
    ),
    path(
        'feed/', LatestPostsFeed(), name='post_feed'
    ),
    path(
        'search/', post_search, name='post_search'
    ),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSiteMap


sitemaps = {'posts': PostSiteMap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(
                    'blog.urls',
                    namespace = 'blog',
                  )
    ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps,},
         name = 'django.contrib.sitemaps.views.sitemaps'
    ),

]

my_site/blog/models.py
from django.contrib.auth import get_user_model
from django.db.models import (CASCADE, BooleanField, CharField,
                              DateTimeField, EmailField, ForeignKey, Manager, Model, SlugField, TextField
                             )
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager


# Create your models here.

class PublishedPostsManager(Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = CharField(
        max_length=255,
    )
    slug = SlugField(
        max_length=255,
        unique_for_date='publish',
    )
    author = ForeignKey(
        get_user_model(),
        on_delete=CASCADE,
        related_name='blog_posts',
    )
    body = TextField()
    publish = DateTimeField(
        default=timezone.now,
    )
    created = DateTimeField(
        auto_now_add=True,
    )
    updated = DateTimeField(
        auto_now=True,
    )
    status = CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft',
    )
    objects = Manager()
    published = PublishedPostsManager()
    tags = TaggableManager()
    is_active = BooleanField(
        default=True,
    )

    class Meta:
        ordering = ('-publish',)
        db_table = 'blogs'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ]
        )


class Comment(Model):
    post = ForeignKey(
        Post,
        on_delete=CASCADE,
        related_name='comments'
    )
    name = CharField(max_length=80)
    email = EmailField()
    body = TextField()
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)
    is_active = BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        db_table = 'comments'

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

my_site/blog/forms.py
from django.forms import (
                          Form, ModelForm, CharField,
                          EmailField, Textarea
                         )

from .models import Comment


class EmailPostForm(Form):
    """
        Форма рассылки записи блога по email
    """
    subcriber_name = CharField(max_length=25)
    subscriber_email = EmailField()
    addressee_email = EmailField()
    comments = CharField(
        required=False,
        widget=Textarea,
    )


class CommentForm(ModelForm):
    """
        Форма коммментария к посту блога
    """
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)


class SeachForm(Form):
    """
        Форма для поиска по сайту
    """
    query = CharField()

my_site/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import (SearchVector, SearchQuery,
                                            SearchRank
                                           )

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SeachForm


# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


# Функция не используется
def post_list(request, tag_slug=None):
    """
        Возвращает список всех опубликованных записей блога.
    """
    # posts = Post.published.all()

    # return render(
    #     request,
    #     'blog/post/list.html',
    #     {
    #         'posts': posts,
    #     }
    # )
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если номер страницы не является целым числом - возвращается первая страница.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц - возвращается последняя страница.
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'page': page,
            'posts': posts,
            'tag': tag,
        }
    )


def post_detail(request, year, month, day, post):
    """
        Возвращяет опредленную запись по ключевому слову и дате
    """
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    # Обработка комментариев к посту
    comments = post.comments.filter(is_active=True)
    new_comment = None

    if request.method == 'POST':
        # Отправка пользователем комментария
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Записываем объект комментария, но сохраняем после приязвки его к посту блога
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tag_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts': similar_posts,
        }
    )


def email_post_share(request, post_id):
    # post = get_object_or_404(Post, id=post_id, status='published')
    post = Post.published.get(id=post_id)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['subcriber_name'],
                cd['subscriber_email'],
                post.title
                )
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title,
                post_url,
                cd['subcriber_name'],
                cd['comments']
                )
            send_mail(
                subject,
                message,
                'admin@myblog.com',
                [cd['addressee_email']]
                )
            sent = True
    else:
        form = EmailPostForm()
    return render(
            request,
            'blog/post/email_share.html',
            {
                'form': form,
                'post': post,
                'sent': sent,
            }
        )


def post_search(request):
    """
        Поиск по постам
    """
    form = SeachForm()
    query = None
    result = []

    if 'query' in request.GET:
        form = SeachForm(request.GET)
    # Вариент простого поиска по заголовкам и телу постов
    # if form.is_valid():
    #     query = form.cleaned_data['query']
    #     result = Post.objects.annotate(
    #         search=SearchVector('title', 'body')
    #     ).filter(search=query)

    # Вариант поиска поиска по заголовкам и телу постов с ранжированием
    # if form.is_valid():
    #     query = form.cleaned_data['query']
    #     search_vector = SearchVector('title', 'body')
    #     search_query = SearchQuery(query)
    #     result = Post.objects.annotate(
    #         search=search_vector,
    #         rank=SearchRank(search_vector, search_query)
    #     ).filter(search=search_query).order_by('-rank')

    # Вариант поиска поиска по заголовкам и телу постов с
    # ранжированием и взвешенными запросами
    if form.is_valid():
        # Вес 'A' = 1.0, 'B' = 0.4, 'C' = 0.2, 'D' = 0.1
        # В результатах поиска выводится статьи рангом выше 0.3
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        result = Post.objects.annotate(
            rank=SearchRank(search_vector, search_query)
        ).filter(rank__gte=0.3).order_by('-rank')
        print(result)

    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            'query': query,
            'result': result,
        }
    )

my_site/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{%  load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
    <a href="{% url 'blog:email_post_share' post.id %}">
        Share this post
    </a>
</p>

<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

{% with comments.count as total_comments %}
<h2>{{ total_comments }} comment {{ total_comments|pluralize }}</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>
    There are no comments yet.
</p>
{% endfor %}

{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="." method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <p>
        <input type="submit" value="Add comment">
    </p>
</form>
{% endif %}
{% endblock %}

my_site/blog/templates/blog/post/email_share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
{% if sent %}
<h1>E-mail succesfully sent</h1>
<p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.addressee_email }}</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}

my_site/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

my_site/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My blog{% endblock %}

{% block content %}
<h1>My blog</h1>
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</h2>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
        {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% empty %}
    -
    {% endfor %}
    {# Tags: {{ post.tags.all|join:", " }} #}
</p>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{# {{ post.body|truncatewords:30|linebreaks }} #}
{{ post.body|markdown|truncatewords_html:30 }}
{% empty %}
No post yet.
{% endfor %}

{% include "pagination.html" with page=posts %}
{# {% include "pagination.html" with page=page_obj %} #}
{% endblock %}

my_site/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
{% if query %}
<h1>Post containing "{{ query }}"</h1>
<h3>
    {% with result.count as total_results %}
    Found {{ total_results }} result {{ total_results|pluralize }}

    {% endwith %}
</h3>
{% for post in result %}
<h4>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    {{ post.body|truncatewords:5 }}
</h4>
{% empty %}
<p>
    There are no results for your query.
</p>
{% endfor %}
<p>
    <a href="{% url 'blog:post_search' %}">Search again here</a>
</p>
{% else %}
<h1>Search for post</h1>
<form action="." method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}